### ISSUE TITLE
lowlevel.library

### ISSUE THREAD

**Issue by pcotter72** [ApolloTeam-dev/AROS#18] opened 2020-09-20 08:13 UTC
Freezes/crashes

**To Reproduce**
From CLI, Avail Flush  hang the machine
play more than one Whdload games  hang the machine

**Architecture**
 - Amiga (including UAE, Vampire cards)
 
 
**CPU**
 -
 - m68k

**Comment by MBeijer** [comment] 2021-03-19 22:15
Duplicate of #3

**Closed as completed** 2021-07-18 15:20 UTC
Labels: bug
