### ISSUE TITLE
Which Ubuntu version do you use to build?

### ISSUE THREAD

**Issue by walkero-gr** [ApolloTeam-dev/AROS#12] opened 2020-08-12 12:35 UTC
**Describe the bug**
Based on the Building page (https://github.com/ApolloTeam-dev/AROS/wiki/Building) a few packages are needed to be installed to build the OS. Which Ubuntu version is used, because on Ubuntu 20.04 I have the following issues:
1. for git-core the apt packager proposes the install of git
2. the libxxf86vm1:i386 does not exist. Should the libxxf86vm-dev be installed instead?

**Comment by hgw77** [comment] 2020-08-20 10:05
I stumbled over the same problem, you need to add `architecture i386`

1. sudo dpkg --add-architecture i386
2. and after `sudo apt-get update`  the `libxxf86vm1:i386` package should be available

this should be metioned in the build docu :-)

**Comment by walkero-gr** [comment] 2020-08-24 17:28
Thank you for your tip... I did that change it now I can install libxxf86vm1:i386 just fine.

**Comment by ronybeck** [comment] 2020-09-02 05:49
I suspect we don't actually need that particular dependency.  Did you try building AROS without this package installed?

I am closing this for now because the issue is more or less resolved.

**Closed as completed by ronybeck** 2020-09-02 05:49 UTC
Labels: bug
